"""
Heat-pump tier-selection scatter (visual aid for the 3-tier x 3-4 capacity rework).

WHY THIS EXISTS
---------------
The 36-cell candidate table (build_cell_candidates.py -> cell_candidates.csv)
is an overcomplication: 36 cells means 36 datasheets to pull and defend. The
decision taken 2026-07-28 is to collapse to 3 performance tiers x 3-4 nominal
capacities = 9-12 datasheets. Picking those cells sensibly needs to be done by
eye against the real distribution, not by another quantile rule, so this script
draws the distribution.

  Y axis      COP @ 5 F (-15 C), max-compressor-speed
  X axis      capacity maintenance = max cap @5 F / rated cap @47 F
  Bubble area appearances in the ERS retrofit data (how often really installed)
  Colour      nominal size band from rated capacity @47 F

INPUT
-----
  ../data/interim/hp_units_joined.csv   one row per AHRI certified unit:
        k    AHRI reference number
        w    ERS appearances (occurrences in the retrofit data)
        cm   capacity maintenance
        cop  COP @ 5 F
        c47  rated capacity @ 47 F, BTU/h
  ../data/interim/hp_buckets.csv        brand / model for labelling (joined on k)

  NOTE (reproducibility gap, carried from METHODOLOGY.md): hp_units_joined.csv
  has no producer script in this repo. It is consumed here as given. Do not
  refresh the tier work without first re-establishing how it is built.

OUTPUT
------
  ../data/interim/tier_scatter.html   self-contained, inline SVG, no CDN,
                                      no build step (repo architecture rule)

METHOD / HONESTY
----------------
- A unit is plotted only if it has all three of cm, cop and c47. That gate is
  quantified in the page header (units dropped, appearances dropped, and which
  field caused it) rather than being silent.
- Bubble radius is proportional to sqrt(appearances) so AREA encodes
  appearances. The two most-installed units (~11k appearances each) would
  otherwise swamp the plot.
- The appearance-weighted terciles drawn as guide lines are a REFERENCE, not
  the proposed tier boundaries. COP @ 5 F piles up hard on 1.80 (NEEP's own
  inclusion floor is 1.75), so its lower tercile lands exactly on the pile --
  which is the point: the guide lines show why a naive quantile cut is a bad
  way to choose these tiers, and why we are choosing by eye.
"""

import json
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
INTERIM = HERE.parent / "data" / "interim"
SRC = INTERIM / "hp_units_joined.csv"
BUCKETS = INTERIM / "hp_buckets.csv"
OUT = INTERIM / "tier_scatter.html"
# Second copy at the repo root, published by deploy.sh so the page has a clean
# shareable URL (…/Energy/tier-scatter.html). Generated bytes, so it is
# gitignored on main and lives only on the gh-pages snapshot.
OUT_PUBLIC = HERE.parent.parent / "tier-scatter.html"

# Nominal size bands (BTU/h @47 F). Chosen to be the sizes an installer talks
# about (1.5 / 2 / 2.5-3 / 3.5+ ton), not to equalise counts.
SIZE_BANDS = [
    ("<18k  (~1.5 ton)", 0, 18000, "#4C9BE8"),
    ("18-24k (~2 ton)", 18000, 24000, "#5BA383"),
    ("24-30k (~2.5 ton)", 24000, 30000, "#E8B94C"),
    ("30-36k (~3 ton)", 30000, 36000, "#E8834C"),
    ("36-48k (~3.5-4 ton)", 36000, 48000, "#C4574C"),
    (">=48k  (5 ton+)", 48000, 10**9, "#7A5AA8"),
]

# Plot window. Values outside are clamped to the edge and marked, not dropped.
X_MIN, X_MAX = 0.15, 1.35   # capacity maintenance
Y_MIN, Y_MAX = 0.5, 3.5     # COP @ 5 F

W, H = 1120, 720
PAD_L, PAD_R, PAD_T, PAD_B = 78, 24, 28, 62


def weighted_quantile(values, weights, q):
    order = np.argsort(values)
    v, w = np.asarray(values)[order], np.asarray(weights)[order]
    cw = np.cumsum(w) / w.sum()
    return float(v[np.searchsorted(cw, q)])


def main():
    df = pd.read_csv(SRC)
    total_units = len(df)
    total_app = int(df["w"].sum())

    miss = {
        "capacity maintenance (cm)": int(df["cm"].isna().sum()),
        "COP @ 5 F (cop)": int(df["cop"].isna().sum()),
        "rated capacity @47 F (c47)": int(df["c47"].isna().sum()),
    }

    d = df.dropna(subset=["cm", "cop", "c47"]).copy()
    kept_units, kept_app = len(d), int(d["w"].sum())

    # brand / model for the tooltip, where we have it
    try:
        b = pd.read_csv(BUCKETS)[["k", "brand", "model"]].drop_duplicates("k")
        d = d.merge(b, on="k", how="left")
    except Exception:
        d["brand"], d["model"] = None, None

    # size band
    def band_of(c47):
        for i, (_lab, lo, hi, _col) in enumerate(SIZE_BANDS):
            if lo <= c47 < hi:
                return i
        return len(SIZE_BANDS) - 1

    d["band"] = d["c47"].apply(band_of)

    cop_t = [weighted_quantile(d["cop"], d["w"], q) for q in (1 / 3, 2 / 3)]
    cm_t = [weighted_quantile(d["cm"], d["w"], q) for q in (1 / 3, 2 / 3)]

    # --- scales -----------------------------------------------------------
    px_w, px_h = W - PAD_L - PAD_R, H - PAD_T - PAD_B

    def sx(v):
        v = min(max(v, X_MIN), X_MAX)
        return PAD_L + (v - X_MIN) / (X_MAX - X_MIN) * px_w

    def sy(v):
        v = min(max(v, Y_MIN), Y_MAX)
        return PAD_T + (1 - (v - Y_MIN) / (Y_MAX - Y_MIN)) * px_h

    max_w = d["w"].max()
    R_MAX, R_MIN = 34.0, 1.6

    def sr(w):
        return R_MIN + (R_MAX - R_MIN) * np.sqrt(w / max_w)

    # draw biggest first so small bubbles stay clickable on top
    d = d.sort_values("w", ascending=False)

    pts = []
    for r in d.itertuples():
        clamped = not (X_MIN <= r.cm <= X_MAX and Y_MIN <= r.cop <= Y_MAX)
        name = " ".join(str(x) for x in (r.brand, r.model) if isinstance(x, str))
        pts.append({
            "x": round(sx(r.cm), 1), "y": round(sy(r.cop), 1),
            "r": round(float(sr(r.w)), 2), "b": int(r.band),
            "w": int(r.w), "cm": round(float(r.cm), 3),
            "cop": round(float(r.cop), 2), "c47": int(r.c47),
            "k": int(r.k), "n": name or f"AHRI {int(r.k)}",
            "cl": 1 if clamped else 0,
        })

    # per-band appearance share, for the legend
    band_stats = []
    for i, (lab, _lo, _hi, col) in enumerate(SIZE_BANDS):
        sub = d[d["band"] == i]
        band_stats.append({
            "label": lab, "colour": col, "units": int(len(sub)),
            "app": int(sub["w"].sum()),
            "pct": round(100 * sub["w"].sum() / kept_app, 1) if kept_app else 0.0,
        })

    # --- 3 COP tiers x 4 capacity bands, appearance share per cell --------
    cap_cells = [("<18k", 0, 18000), ("18-30k", 18000, 30000),
                 ("30-42k", 30000, 42000), (">=42k", 42000, 10**9)]
    cop_cells = [("low  (COP < %.2f)" % cop_t[0], -1e9, cop_t[0]),
                 ("mid  (%.2f-%.2f)" % (cop_t[0], cop_t[1]), cop_t[0], cop_t[1]),
                 ("high (COP >= %.2f)" % cop_t[1], cop_t[1], 1e9)]
    grid = []
    for clab, clo, chi in cop_cells:
        row = []
        for plab, plo, phi in cap_cells:
            sub = d[(d.cop >= clo) & (d.cop < chi) & (d.c47 >= plo) & (d.c47 < phi)]
            row.append({"units": int(len(sub)), "app": int(sub["w"].sum()),
                        "pct": round(100 * sub["w"].sum() / kept_app, 1)})
        grid.append({"label": clab, "cells": row})

    meta = {
        "total_units": total_units, "total_app": total_app,
        "kept_units": kept_units, "kept_app": kept_app,
        "app_pct": round(100 * kept_app / total_app, 1),
        "missing": miss, "cop_terciles": [round(v, 2) for v in cop_t],
        "cm_terciles": [round(v, 3) for v in cm_t],
        "cap_labels": [c[0] for c in cap_cells],
    }

    html = render(pts, band_stats, meta, grid, sx, sy)
    OUT.write_text(html, encoding="utf-8")
    OUT_PUBLIC.write_text(html, encoding="utf-8")
    print(f"wrote {OUT}\nwrote {OUT_PUBLIC}")
    print(f"  {kept_units:,} of {total_units:,} units plotted; "
          f"{kept_app:,} of {total_app:,} appearances ({meta['app_pct']}%)")
    print(f"  COP terciles {meta['cop_terciles']}  CM terciles {meta['cm_terciles']}")


def render(pts, bands, meta, grid, sx, sy):
    # axis ticks
    xticks = "".join(
        f'<line x1="{sx(v):.1f}" y1="{PAD_T}" x2="{sx(v):.1f}" y2="{H-PAD_B}" class="g"/>'
        f'<text x="{sx(v):.1f}" y="{H-PAD_B+20}" class="tk" text-anchor="middle">{int(v*100)}%</text>'
        for v in np.arange(0.2, 1.35, 0.1))
    yticks = "".join(
        f'<line x1="{PAD_L}" y1="{sy(v):.1f}" x2="{W-PAD_R}" y2="{sy(v):.1f}" class="g"/>'
        f'<text x="{PAD_L-10}" y="{sy(v)+4:.1f}" class="tk" text-anchor="end">{v:.1f}</text>'
        for v in np.arange(1.0, 3.6, 0.5))

    guides = "".join(
        f'<line x1="{PAD_L}" y1="{sy(v):.1f}" x2="{W-PAD_R}" y2="{sy(v):.1f}" class="q"/>'
        f'<text x="{W-PAD_R-6}" y="{sy(v)-5:.1f}" class="qt" text-anchor="end">COP tercile {v:.2f}</text>'
        for v in meta["cop_terciles"]) + "".join(
        f'<line x1="{sx(v):.1f}" y1="{PAD_T}" x2="{sx(v):.1f}" y2="{H-PAD_B}" class="q"/>'
        f'<text x="{sx(v)+5:.1f}" y="{PAD_T+14}" class="qt">CM tercile {v*100:.0f}%</text>'
        for v in meta["cm_terciles"])

    legend = "".join(
        f'<label class="lg"><input type="checkbox" data-band="{i}" checked>'
        f'<span class="sw" style="background:{b["colour"]}"></span>'
        f'{b["label"]} <em>{b["pct"]}% of installs · {b["units"]:,} units</em></label>'
        for i, b in enumerate(bands))

    head = "".join(f"<th>{c}</th>" for c in meta["cap_labels"])
    rows = "".join(
        "<tr><th>" + g["label"] + "</th>" + "".join(
            f'<td><b>{c["pct"]}%</b><span>{c["units"]:,} units</span></td>'
            for c in g["cells"]) + "</tr>"
        for g in grid)

    miss = " · ".join(f"{k}: {v:,}" for k, v in meta["missing"].items())

    return f"""<!doctype html>
<meta charset="utf-8">
<title>Heat-pump tier selection — COP @ 5 °F vs capacity maintenance</title>
<style>
  :root {{ --ink:#12202E; --dim:#5A6B7C; --line:#D9E1EA; --paper:#fff; }}
  * {{ box-sizing:border-box }}
  body {{ margin:0; padding:26px 30px 60px; background:#F4F7FA; color:var(--ink);
         font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif }}
  h1 {{ font-size:21px; margin:0 0 4px }}
  h2 {{ font-size:15px; margin:26px 0 8px; text-transform:uppercase;
        letter-spacing:.06em; color:var(--dim) }}
  .sub {{ color:var(--dim); max-width:80ch; margin:0 0 16px }}
  .temp {{ background:#FFF4D6; border:1px solid #E8C86A; border-radius:8px;
           padding:9px 13px; font-size:13px; margin:0 0 16px; max-width:88ch }}
  .card {{ background:var(--paper); border:1px solid var(--line); border-radius:10px;
           padding:16px 18px; margin-bottom:18px }}
  .gate {{ font-size:13px; color:var(--dim); border-left:3px solid #E8B94C;
           padding:6px 0 6px 12px; margin:12px 0 0 }}
  svg {{ display:block; max-width:100%; height:auto }}
  .g {{ stroke:#EDF1F5; stroke-width:1 }}
  .q {{ stroke:#B9C6D4; stroke-width:1; stroke-dasharray:5 4 }}
  .qt {{ font-size:10.5px; fill:#8797A6 }}
  .tk {{ font-size:11px; fill:var(--dim) }}
  .ax {{ font-size:12.5px; fill:var(--ink); font-weight:600 }}
  circle.pt {{ stroke:#fff; stroke-width:.7; cursor:pointer }}
  circle.pt.clamped {{ stroke:#12202E; stroke-width:1.4; stroke-dasharray:2 2 }}
  .legend {{ display:flex; flex-wrap:wrap; gap:6px 22px; margin-top:12px }}
  .lg {{ display:flex; align-items:center; gap:7px; font-size:13px; cursor:pointer;
         user-select:none }}
  .lg em {{ color:var(--dim); font-style:normal; font-size:12px }}
  .sw {{ width:13px; height:13px; border-radius:50%; display:inline-block }}
  #tip {{ position:fixed; pointer-events:none; opacity:0; transition:opacity .1s;
          background:#12202E; color:#fff; padding:8px 11px; border-radius:7px;
          font-size:12.5px; line-height:1.5; z-index:9; max-width:280px }}
  #tip b {{ font-size:13px }}
  table {{ border-collapse:collapse; font-size:13px }}
  th, td {{ border:1px solid var(--line); padding:7px 12px; text-align:center }}
  thead th, tbody th {{ background:#EDF2F7; font-weight:600; text-align:left;
                        white-space:nowrap }}
  td b {{ display:block; font-size:15px }}
  td span {{ color:var(--dim); font-size:11.5px }}
  .ctl {{ font-size:13px; color:var(--dim); margin-top:10px }}
</style>

<p class="temp"><b>Working document — for discussion, not a published result.</b>
An internal selection aid for the Energy Suite heat-pump tool: temporary, not linked
from the site, and to be removed once the tier cells are chosen. Nothing here is a
recommendation about any product.</p>

<h1>Heat-pump tier selection — COP @ 5 °F vs capacity maintenance</h1>
<p class="sub">Every AHRI-certified unit that appears in the ERS retrofit data, positioned by
cold-climate efficiency and capacity retention, sized by how often it was actually installed.
Use it to place <b>3 performance tiers × 3–4 nominal capacities</b> by eye — replacing the
36-cell candidate table.</p>

<div class="card">
  <svg viewBox="0 0 {W} {H}" id="plot">
    <rect x="{PAD_L}" y="{PAD_T}" width="{W-PAD_L-PAD_R}" height="{H-PAD_T-PAD_B}"
          fill="#fff" stroke="#D9E1EA"/>
    {xticks}{yticks}{guides}
    <g id="pts"></g>
    <text x="{PAD_L+(W-PAD_L-PAD_R)/2}" y="{H-16}" class="ax" text-anchor="middle">
      Capacity maintenance — max capacity @ 5 °F ÷ rated capacity @ 47 °F</text>
    <text x="18" y="{PAD_T+(H-PAD_T-PAD_B)/2}" class="ax" text-anchor="middle"
          transform="rotate(-90 18 {PAD_T+(H-PAD_T-PAD_B)/2})">COP @ 5 °F (−15 °C)</text>
  </svg>
  <div class="legend">{legend}</div>
  <p class="ctl">Bubble <b>area</b> ∝ ERS appearances. Dashed-outline bubbles sit outside the
  plot window and are clamped to the edge, not dropped. Hover any bubble for its identity.</p>
  <p class="gate"><b>Gate:</b> {meta['kept_units']:,} of {meta['total_units']:,} units plotted,
  covering {meta['kept_app']:,} of {meta['total_app']:,} ERS appearances
  (<b>{meta['app_pct']}%</b>). Dropped: units missing any of the three plotted metrics —
  {miss}. Nothing is imputed.</p>
</div>

<h2>Where the installs actually are — 3 COP tiers × 4 capacity bands</h2>
<p class="sub">Share of plotted ERS appearances per cell. This is the "which 12 datasheets"
question in table form; the COP splits are the appearance-weighted terciles drawn on the plot.</p>
<div class="card" style="display:inline-block">
  <table>
    <thead><tr><th>COP @ 5 °F tier</th>{head}</tr></thead>
    <tbody>{rows}</tbody>
  </table>
</div>

<div id="tip"></div>
<script>
const PTS = {json.dumps(pts, separators=(",", ":"))};
const COL = {json.dumps([b["colour"] for b in bands])};
const g = document.getElementById('pts'), tip = document.getElementById('tip');
const on = new Set(COL.map((_, i) => i));

function draw() {{
  g.innerHTML = PTS.map((p, i) => on.has(p.b) ?
    `<circle class="pt${{p.cl ? ' clamped' : ''}}" cx="${{p.x}}" cy="${{p.y}}" r="${{p.r}}"
      fill="${{COL[p.b]}}" fill-opacity=".55" data-i="${{i}}"/>` : '').join('');
}}
draw();

document.querySelectorAll('.lg input').forEach(cb => cb.onchange = () => {{
  const b = +cb.dataset.band;
  cb.checked ? on.add(b) : on.delete(b);
  draw();
}});

g.addEventListener('mouseover', e => {{
  if (e.target.tagName !== 'circle') return;
  const p = PTS[+e.target.dataset.i];
  tip.innerHTML = `<b>${{p.n}}</b><br>AHRI ${{p.k}}<br>
    COP @ 5 °F <b>${{p.cop}}</b> · capacity maintenance <b>${{(p.cm*100).toFixed(0)}}%</b><br>
    rated ${{p.c47.toLocaleString()}} BTU/h @ 47 °F<br>
    <b>${{p.w.toLocaleString()}}</b> ERS appearance${{p.w === 1 ? '' : 's'}}` +
    (p.cl ? '<br><i>clamped to plot edge</i>' : '');
  tip.style.opacity = 1;
}});
g.addEventListener('mousemove', e => {{
  tip.style.left = Math.min(e.clientX + 16, innerWidth - 300) + 'px';
  tip.style.top = (e.clientY + 16) + 'px';
}});
g.addEventListener('mouseout', () => tip.style.opacity = 0);
</script>
"""


if __name__ == "__main__":
    main()
